updated README for ADCG to TTWG
w3c/adpt pull request #21
Opened 2019-11-25 11:11 UTC by himorin

updated for #20

2019-11-25 12:37 UTC, nigelmegitt requested changes
We need to credit the AD CG also with their work on this, somehow. In some ways it's a joint project between a CG and a WG, a bit like WebVTT.

2019-11-27 07:18 UTC, himorin commented
I'm a bit unsure which is a way to go, mentioning audio description CG as WebVTT (but actually transferred to TTWG not like WebVTT?) or joint work of CG/WG, but how about as ee8d8ec?

2019-11-27 09:34 UTC, plehegar approved these changes

2019-11-27 15:21 UTC, nigelmegitt approved these changes
Looks good to me too.

2019-11-27 15:39 UTC, merged